### ISSUE TITLE
Different icons

### ISSUE THREAD

**Issue by sabas** [H2OpenMap/map#3]
Display different icons based on water well types.

**Comment by francesco25674** [comment]
the goal is to provide directly on the H2OpenMap map more information about the water well just by the icons:
![water_tap](https://cloud.githubusercontent.com/assets/11157871/12818754/6516e8ae-cb58-11e5-89b4-87f6e1d5d311.png) 
to use when the water resource is not man_made=water_well but amenity:drinking_water.

![small_diam](https://cloud.githubusercontent.com/assets/11157871/12818781/84e02042-cb58-11e5-9923-210558814a27.png) 
general icon for drilled water well

![pedal](https://cloud.githubusercontent.com/assets/11157871/12818883/f23ececc-cb58-11e5-88f8-af58ebbabbbc.png) 
to use for water well like this
![copia di dscn1237](https://cloud.githubusercontent.com/assets/11157871/12819476/978f6ec0-cb5b-11e5-8803-1dfc7217bc35.jpg)

![manual](https://cloud.githubusercontent.com/assets/11157871/12819088/f1e87ff8-cb59-11e5-8613-929615956476.png)
to use for water well like this
![dscn1252](https://cloud.githubusercontent.com/assets/11157871/12819673/4d8145b4-cb5c-11e5-932d-1f93ae38e738.jpg)

![large_diam](https://cloud.githubusercontent.com/assets/11157871/12819215/67b66dda-cb5a-11e5-819c-f6c96e403853.png)
to use for water well like this
![dscn1226](https://cloud.githubusercontent.com/assets/11157871/12819590/f18b36ac-cb5b-11e5-94cd-d45476ff5df3.jpg)

![flywheel](https://cloud.githubusercontent.com/assets/11157871/12819245/9ba35888-cb5a-11e5-9530-2bdd79bf3803.png)
to use for water well like this
![dscn1199](https://cloud.githubusercontent.com/assets/11157871/12819631/15c9b9b2-cb5c-11e5-9e7f-01bb3e45251c.jpg)


as same time, changing color of the water is also possible to tell:

![large_diam](https://cloud.githubusercontent.com/assets/11157871/12820525/b9468fc2-cb5f-11e5-8d84-241d553080c4.png)
clean or drinking water


![large_diam_no_drinking](https://cloud.githubusercontent.com/assets/11157871/12820542/cf87922c-cb5f-11e5-9f4d-0bc284764dcd.png)
visibly not drinking water


![large_diam_no_water](https://cloud.githubusercontent.com/assets/11157871/12820556/dfc0d810-cb5f-11e5-9a18-c63b3dbcf9b4.png)
dry or broken water well

the icons should have standard dimensions 16x16 pixels:
![flywheel](https://cloud.githubusercontent.com/assets/11157871/12821167/89825a16-cb62-11e5-8323-4f462a4ba27d.png)
![india16](https://cloud.githubusercontent.com/assets/11157871/12821168/899b1b00-cb62-11e5-9478-f2d1f69e2e99.png)
![large_diam_no_drinking](https://cloud.githubusercontent.com/assets/11157871/12821170/89cfabcc-cb62-11e5-96b2-f83e7b371e3e.png)
![large_diam_no_water](https://cloud.githubusercontent.com/assets/11157871/12821169/89b86ba6-cb62-11e5-9b15-d52958f77807.png)
![large_diam](https://cloud.githubusercontent.com/assets/11157871/12821172/89e1109c-cb62-11e5-83f2-813280310e83.png)
![manual](https://cloud.githubusercontent.com/assets/11157871/12821173/89e83fa2-cb62-11e5-9142-f7f93af12407.png)
![pedal](https://cloud.githubusercontent.com/assets/11157871/12821171/89df958c-cb62-11e5-951b-2149f6e8f33e.png)
![water_tap](https://cloud.githubusercontent.com/assets/11157871/12821174/89eb032c-cb62-11e5-96ec-613b9606cb2e.png)

so, maybe for some icon can be difficult to distinguish clean, not drinking or dry condition? some improvement is needed
![manual](https://cloud.githubusercontent.com/assets/11157871/12821612/5d3aa9de-cb64-11e5-8359-c4084ef984c2.png) clean or drinking water
![manual_no_drink](https://cloud.githubusercontent.com/assets/11157871/12821611/5d32db32-cb64-11e5-99fa-5c6f3259d348.png) putrid o visibly not drinking water
![manual_dry](https://cloud.githubusercontent.com/assets/11157871/12821610/5d294108-cb64-11e5-8b5c-45ef5c61cb3d.png) dry

**Comment by francesco25674** [comment]
this is 2nd version icons 20x20px, drinking_water=yes, drinking_water=[no], dry=yes:

![20_fly_2 1](https://cloud.githubusercontent.com/assets/11157871/13027142/f220b256-d243-11e5-991f-9cba1b90c35a.png) ![20_fly_2 2](https://cloud.githubusercontent.com/assets/11157871/13027143/f222ce4c-d243-11e5-8ba1-6e4110a5ed60.png) ![20_fly_2 3 1](https://cloud.githubusercontent.com/assets/11157871/13027144/f22a441a-d243-11e5-8abc-4cbd44b61039.png)

![20_hand_2 1](https://cloud.githubusercontent.com/assets/11157871/13027148/0ad72f1e-d244-11e5-862d-d83d5f820704.png) ![20_hand_2 2](https://cloud.githubusercontent.com/assets/11157871/13027150/0ae26d0c-d244-11e5-8ba3-0e5f24ab3eae.png) ![20_hand_2 3 1](https://cloud.githubusercontent.com/assets/11157871/13027156/3fbb8d24-d244-11e5-8824-c79cab234992.png)

![20_large_2 1](https://cloud.githubusercontent.com/assets/11157871/13027157/4a1d941a-d244-11e5-8373-6f018c269663.png) ![20_large_2 2](https://cloud.githubusercontent.com/assets/11157871/13027158/4a21f226-d244-11e5-85d1-096a01424ef9.png) ![20_large_2 3 1](https://cloud.githubusercontent.com/assets/11157871/13027159/4a282e2a-d244-11e5-98c7-ff15c6d16278.png)

![20_pedal_2 1](https://cloud.githubusercontent.com/assets/11157871/13027162/59d3c424-d244-11e5-8aca-646896dc3fb6.png) ![20_pedal_2 2](https://cloud.githubusercontent.com/assets/11157871/13027163/59d8ba7e-d244-11e5-9e3c-06721c57f293.png) ![20_pedal_2 3 1](https://cloud.githubusercontent.com/assets/11157871/13027164/59e08a6a-d244-11e5-993c-63a58ce10adb.png)

![20_tap_2 1](https://cloud.githubusercontent.com/assets/11157871/13027166/74abc44a-d244-11e5-80c5-aa25481506a0.png) ![20_tap_2 2](https://cloud.githubusercontent.com/assets/11157871/13027167/74b08ae8-d244-11e5-8982-676e1bb0685d.png) ![20_tap_2 3 2](https://cloud.githubusercontent.com/assets/11157871/13027168/74b82488-d244-11e5-85cd-33db3659beb1.png)

if drinking_water or dry is not defined  we will use a generic icon:
![20_fly_2 3](https://cloud.githubusercontent.com/assets/11157871/13027233/c92a4e68-d246-11e5-84cf-77035154549b.png)
![20_hand_2 3](https://cloud.githubusercontent.com/assets/11157871/13027234/c931a2bc-d246-11e5-942c-e58c1ead1ee7.png)
![20_large_2 3](https://cloud.githubusercontent.com/assets/11157871/13027235/c934bff6-d246-11e5-969f-b920c4588987.png)
![20_pedal_2 3](https://cloud.githubusercontent.com/assets/11157871/13027237/c9b8d444-d246-11e5-9ef2-1495e79c6538.png)
![20_tap_2 3](https://cloud.githubusercontent.com/assets/11157871/13027236/c9990e84-d246-11e5-93d9-393ad1c283b9.png)

**Comment by francesco25674** [comment]
added generic icon for unknow water well
![20_drop_1](https://cloud.githubusercontent.com/assets/11157871/13028521/aa9e838a-d271-11e5-958d-3a41a415fe5b.png)
this icon is temporary and no so nice

**Comment by francesco25674** [comment]
for the moment we have sufficient quality.....
